'use strict';

const $ = (s) => document.querySelector(s);
const $$ = (s) => Array.from(document.querySelectorAll(s));
const state = {
  lat: null, lon: null,
  timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'Europe/Warsaw',
  location: 'Текущая позиция', weather: null, hours: [], filter: 'all',
  installPrompt: null, lang: localStorage.getItem('lunarisLang') || 'ru', timers: new Map()
};
const locales={ru:'ru-RU',uk:'uk-UA',kk:'kk-KZ',be:'be-BY',pl:'pl-PL',en:'en-US'};
const copy={
ru:{today:'Сегодня',hours:'Планетарные часы',planner:'Планировщик',weather:'Погода',install:'Установить приложение',localTime:'ВАШЕ МЕСТНОЕ ВРЕМЯ',auto:'Местное время, погода, Луна и планетарный час определяются автоматически — без ввода города.',plan:'＋ Запланировать практику',locating:'Определяем ваше местоположение…',sync:'Синхронизация…',now:'СЕЙЧАС',atmos:'АТМОСФЕРА',full:'БЛИЖАЙШЕЕ ПОЛНОЛУНИЕ',all:'Все',day:'День',night:'Ночь',add:'＋ Добавить практику',sunrise:'Восход',sunset:'Закат',created:'Создано Орденом VERBUM DAEMONIS',tool:'Цифровой инструмент для планирования ритуально-обрядовых практик.',phase:['Новолуние','Растущий серп','Первая четверть','Растущая Луна','Полнолуние','Убывающая Луна','Последняя четверть','Убывающий серп'],current:'Сейчас',updated:'Обновлено',feels:'Ощущается как',records:['запись','записи','записей'],empty:'Здесь появятся ваши будущие практики.',nothing:'Пока ничего не запланировано',first:'Добавьте первую практику — это займёт меньше минуты.',nearest:'БЛИЖАЙШАЯ',notify:'Напомним за час',saved:'Практика сохранена',permission:'Разрешите уведомления, чтобы получить напоминание.',geoDenied:'Разрешите геолокацию для точных местных данных.',installed:'LUNARIS установлен',installTitle:'Установить LUNARIS',installLead:'Приложение появится на главном экране или рабочем столе и будет открываться как самостоятельная программа.',manual:'Откройте меню браузера и выберите «Установить приложение» или «Добавить на главный экран».',ios:'В Safari нажмите «Поделиться», затем «На экран Домой» и «Добавить».',ok:'Понятно'},
uk:{today:'Сьогодні',hours:'Планетарні години',planner:'Планувальник',weather:'Погода',install:'Встановити застосунок',localTime:'ВАШ МІСЦЕВИЙ ЧАС',auto:'Місцевий час, погода, Місяць і планетарна година визначаються автоматично — без введення міста.',plan:'＋ Запланувати практику',locating:'Визначаємо ваше місцезнаходження…',sync:'Синхронізація…',now:'ЗАРАЗ',atmos:'АТМОСФЕРА',full:'НАЙБЛИЖЧИЙ ПОВНИЙ МІСЯЦЬ',all:'Усі',day:'День',night:'Ніч',add:'＋ Додати практику',sunrise:'Схід',sunset:'Захід',created:'Створено Орденом VERBUM DAEMONIS',tool:'Цифровий інструмент для планування ритуально-обрядових практик.',phase:['Молодик','Зростаючий серп','Перша чверть','Зростаючий Місяць','Повня','Спадний Місяць','Остання чверть','Спадний серп'],current:'Зараз',updated:'Оновлено',feels:'Відчувається як',records:['запис','записи','записів'],empty:'Тут з’являться ваші майбутні практики.',nothing:'Поки нічого не заплановано',first:'Додайте першу практику — це займе менше хвилини.',nearest:'НАЙБЛИЖЧА',notify:'Нагадаємо за годину',saved:'Практику збережено',permission:'Дозвольте сповіщення, щоб отримати нагадування.',geoDenied:'Дозвольте геолокацію для точних місцевих даних.',installed:'LUNARIS встановлено',installTitle:'Встановити LUNARIS',installLead:'Застосунок з’явиться на головному екрані або робочому столі.',manual:'Відкрийте меню браузера та виберіть «Встановити застосунок» або «Додати на головний екран».',ios:'У Safari натисніть «Поділитися», потім «На початковий екран» і «Додати».',ok:'Зрозуміло'},
kk:{today:'Бүгін',hours:'Планеталық сағаттар',planner:'Жоспарлаушы',weather:'Ауа райы',install:'Қолданбаны орнату',localTime:'СІЗДІҢ ЖЕРГІЛІКТІ УАҚЫТЫҢЫЗ',auto:'Жергілікті уақыт, ауа райы, Ай және планеталық сағат қала енгізбей автоматты анықталады.',plan:'＋ Тәжірибені жоспарлау',locating:'Орныңыз анықталуда…',sync:'Синхрондау…',now:'ҚАЗІР',atmos:'АТМОСФЕРА',full:'КЕЛЕСІ ТОЛҒАН АЙ',all:'Барлығы',day:'Күн',night:'Түн',add:'＋ Тәжірибе қосу',sunrise:'Күн шығуы',sunset:'Күн батуы',created:'VERBUM DAEMONIS Ордені жасаған',tool:'Рәсімдік тәжірибелерді жоспарлауға арналған цифрлық құрал.',phase:['Жаңа ай','Өсуші орақ','Бірінші ширек','Өсуші ай','Толған ай','Кемуші ай','Соңғы ширек','Кемуші орақ'],current:'Қазір',updated:'Жаңартылды',feels:'Сезіледі',records:['жазба','жазба','жазба'],empty:'Болашақ тәжірибелеріңіз осында көрінеді.',nothing:'Әзірге ештеңе жоспарланбаған',first:'Алғашқы тәжірибені қосыңыз.',nearest:'КЕЛЕСІ',notify:'Бір сағат бұрын еске саламыз',saved:'Тәжірибе сақталды',permission:'Еске салу үшін хабарландыруға рұқсат беріңіз.',geoDenied:'Нақты деректер үшін геолокацияға рұқсат беріңіз.',installed:'LUNARIS орнатылды',installTitle:'LUNARIS орнату',installLead:'Қолданба негізгі экранда немесе жұмыс үстелінде пайда болады.',manual:'Браузер мәзірінен «Қолданбаны орнату» немесе «Басты экранға қосу» таңдаңыз.',ios:'Safari-де «Бөлісу», кейін «Басты экранға» және «Қосу» таңдаңыз.',ok:'Түсінікті'},
be:{today:'Сёння',hours:'Планетарныя гадзіны',planner:'Планавальнік',weather:'Надвор’е',install:'Усталяваць праграму',localTime:'ВАШ МЯСЦОВЫ ЧАС',auto:'Мясцовы час, надвор’е, Месяц і планетарная гадзіна вызначаюцца аўтаматычна — без уводу горада.',plan:'＋ Запланаваць практыку',locating:'Вызначаем ваша месцазнаходжанне…',sync:'Сінхранізацыя…',now:'ЦЯПЕР',atmos:'АТМАСФЕРА',full:'БЛІЖЭЙШАЯ ПОЎНЯ',all:'Усе',day:'Дзень',night:'Ноч',add:'＋ Дадаць практыку',sunrise:'Усход',sunset:'Захад',created:'Створана Ордэнам VERBUM DAEMONIS',tool:'Лічбавы інструмент для планавання рытуальна-абрадавых практык.',phase:['Маладзік','Месяц расце','Першая чвэрць','Месяц расце','Поўня','Месяц змяншаецца','Апошняя чвэрць','Стары месяц'],current:'Цяпер',updated:'Абноўлена',feels:'Адчуваецца як',records:['запіс','запісы','запісаў'],empty:'Тут з’явяцца вашы будучыя практыкі.',nothing:'Пакуль нічога не запланавана',first:'Дадайце першую практыку.',nearest:'БЛІЖЭЙШАЯ',notify:'Нагадаем за гадзіну',saved:'Практыка захавана',permission:'Дазвольце апавяшчэнні для напаміну.',geoDenied:'Дазвольце геалакацыю для дакладных мясцовых даных.',installed:'LUNARIS усталяваны',installTitle:'Усталяваць LUNARIS',installLead:'Праграма з’явіцца на галоўным экране або працоўным стале.',manual:'Адкрыйце меню браўзера і выберыце «Усталяваць праграму» або «Дадаць на галоўны экран».',ios:'У Safari націсніце «Падзяліцца», потым «На пачатковы экран» і «Дадаць».',ok:'Зразумела'},
pl:{today:'Dzisiaj',hours:'Godziny planetarne',planner:'Planer',weather:'Pogoda',install:'Zainstaluj aplikację',localTime:'TWÓJ CZAS LOKALNY',auto:'Czas lokalny, pogoda, Księżyc i godzina planetarna są ustalane automatycznie — bez wpisywania miasta.',plan:'＋ Zaplanuj praktykę',locating:'Ustalamy Twoją lokalizację…',sync:'Synchronizacja…',now:'TERAZ',atmos:'ATMOSFERA',full:'NAJBLIŻSZA PEŁNIA',all:'Wszystkie',day:'Dzień',night:'Noc',add:'＋ Dodaj praktykę',sunrise:'Wschód',sunset:'Zachód',created:'Stworzone przez Zakon VERBUM DAEMONIS',tool:'Cyfrowe narzędzie do planowania praktyk rytualno-obrzędowych.',phase:['Nów','Przybywający sierp','Pierwsza kwadra','Księżyc przybywa','Pełnia','Księżyc ubywa','Ostatnia kwadra','Ubywający sierp'],current:'Teraz',updated:'Zaktualizowano',feels:'Odczuwalna',records:['wpis','wpisy','wpisów'],empty:'Tutaj pojawią się Twoje przyszłe praktyki.',nothing:'Nic jeszcze nie zaplanowano',first:'Dodaj pierwszą praktykę.',nearest:'NAJBLIŻSZA',notify:'Przypomnimy godzinę wcześniej',saved:'Praktyka zapisana',permission:'Zezwól na powiadomienia, aby otrzymać przypomnienie.',geoDenied:'Zezwól na lokalizację, aby uzyskać dokładne dane.',installed:'LUNARIS zainstalowany',installTitle:'Zainstaluj LUNARIS',installLead:'Aplikacja pojawi się na ekranie głównym lub pulpicie.',manual:'Otwórz menu przeglądarki i wybierz „Zainstaluj aplikację” lub „Dodaj do ekranu głównego”.',ios:'W Safari wybierz „Udostępnij”, następnie „Do ekranu początkowego” i „Dodaj”.',ok:'Rozumiem'},
en:{today:'Today',hours:'Planetary hours',planner:'Planner',weather:'Weather',install:'Install app',localTime:'YOUR LOCAL TIME',auto:'Local time, weather, Moon and planetary hour are detected automatically — no city entry needed.',plan:'＋ Plan a practice',locating:'Detecting your location…',sync:'Synchronizing…',now:'NOW',atmos:'ATMOSPHERE',full:'NEXT FULL MOON',all:'All',day:'Day',night:'Night',add:'＋ Add practice',sunrise:'Sunrise',sunset:'Sunset',created:'Created by the Order VERBUM DAEMONIS',tool:'A digital tool for planning ritual and ceremonial practices.',phase:['New Moon','Waxing crescent','First quarter','Waxing Moon','Full Moon','Waning Moon','Last quarter','Waning crescent'],current:'Now',updated:'Updated',feels:'Feels like',records:['entry','entries','entries'],empty:'Your future practices will appear here.',nothing:'Nothing planned yet',first:'Add your first practice.',nearest:'NEXT',notify:'We will remind you one hour before',saved:'Practice saved',permission:'Allow notifications to receive a reminder.',geoDenied:'Allow location access for accurate local data.',installed:'LUNARIS installed',installTitle:'Install LUNARIS',installLead:'The app will appear on your home screen or desktop.',manual:'Open the browser menu and choose “Install app” or “Add to Home Screen”.',ios:'In Safari, tap Share, then Add to Home Screen, then Add.',ok:'Got it'}};
const T=()=>copy[state.lang]||copy.ru;
const locale=()=>locales[state.lang]||locales.ru;
const weatherCodes={0:['Ясно','☀'],1:['Преимущественно ясно','◒'],2:['Переменная облачность','⛅'],3:['Пасмурно','☁'],45:['Туман','≋'],48:['Изморозь','≋'],51:['Морось','⌁'],53:['Морось','⌁'],55:['Сильная морось','⌁'],61:['Небольшой дождь','☂'],63:['Дождь','☂'],65:['Сильный дождь','☂'],71:['Небольшой снег','✦'],73:['Снег','✦'],75:['Сильный снег','✦'],80:['Ливни','☂'],81:['Сильные ливни','☂'],82:['Очень сильные ливни','☂'],95:['Гроза','ϟ'],96:['Гроза с градом','ϟ'],99:['Сильная гроза','ϟ']};
const planets={Saturn:{name:'Сатурна',seal:'♄',tags:['границы','защита','завершение'],note:'Для дисциплины, защиты, отсечения и завершения.'},Jupiter:{name:'Юпитера',seal:'♃',tags:['достаток','авторитет','рост'],note:'Для расширения, благополучия, статуса и удачи.'},Mars:{name:'Марса',seal:'♂',tags:['сила','решимость','отсечение'],note:'Для решительных действий, силы и преодоления.'},Sun:{name:'Солнца',seal:'☉',tags:['ясность','успех','жизненная сила'],note:'Для признания, ясности, здоровья и лидерства.'},Venus:{name:'Венеры',seal:'♀',tags:['гармония','красота','притяжение'],note:'Для отношений, примирения, искусства и притяжения.'},Mercury:{name:'Меркурия',seal:'☿',tags:['знание','речь','дороги'],note:'Для обучения, переговоров, письма и торговли.'},Moon:{name:'Луны',seal:'☽',tags:['интуиция','сны','очищение'],note:'Для сновидений, внутренней работы, воды и циклов.'}};
const order=['Saturn','Jupiter','Mars','Sun','Venus','Mercury','Moon'],dayRulers=['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn'];
const SYNODIC=29.530588853, REF_NEW=Date.UTC(2000,0,6,18,14);
const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(text){const e=$('#toast');if(!e)return;e.textContent=text;e.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('show'),3200)}
function setStatus(text){if($('#statusLine'))$('#statusLine').textContent=text;if($('#syncLabel'))$('#syncLabel').textContent=text}
function fmtTime(d){return new Intl.DateTimeFormat(locale(),{hour:'2-digit',minute:'2-digit',timeZone:state.timezone}).format(new Date(d))}
function fmtDate(d){return new Intl.DateTimeFormat(locale(),{day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:state.timezone}).format(new Date(d))}
function localDate(d=new Date()){return new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:state.timezone}).format(d)}
function localTime(d=new Date()){return new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:state.timezone}).format(d)}
function applyLanguage(lang){state.lang=copy[lang]?lang:'ru';localStorage.setItem('lunarisLang',state.lang);document.documentElement.lang=state.lang;['languageSelect','languageSelectMobile'].forEach(id=>{const e=$('#'+id);if(e)e.value=state.lang});const t=T();const nav=$$('.sidebar nav a span');if(nav[0])nav[0].textContent=t.today;if(nav[1])nav[1].textContent=t.hours;if(nav[2])nav[2].textContent=t.planner;if(nav[3])nav[3].textContent=t.weather;$('#sidebarInstallBtn').textContent='↓ '+t.install;$('#installBtn').textContent='↓ '+t.install;$('.kicker').lastChild.textContent=t.localTime;$('.hero-copy>p:not(.kicker)').textContent=t.auto;$('#quickPlanBtn').textContent=t.plan;$('#newPracticeBtn').textContent=t.add;const eyes=$$('.quick-grid .eyebrow');if(eyes[0])eyes[0].textContent=t.now;if(eyes[1])eyes[1].textContent=t.atmos;if(eyes[2])eyes[2].textContent=t.full;const seg=$$('.segmented button');if(seg[0])seg[0].textContent=t.all;if(seg[1])seg[1].textContent=t.day;if(seg[2])seg[2].textContent=t.night;const sunLabels=$$('.sun-times span');if(sunLabels[0])sunLabels[0].textContent=t.sunrise;if(sunLabels[1])sunLabels[1].textContent=t.sunset;const credit=$('.order-credit small');if(credit)credit.textContent=t.tool;renderMoon();renderHours();renderPractices();if(state.weather)renderWeather(state.weather)}
function moonData(date=new Date()){const days=(date-REF_NEW)/864e5,age=((days%SYNODIC)+SYNODIC)%SYNODIC,phase=age/SYNODIC,illum=(1-Math.cos(2*Math.PI*phase))/2;return{phase,illum,name:T().phase[Math.round(phase*8)%8]}}
function nextFullMoon(now=new Date()){const days=(now-REF_NEW)/864e5,l=Math.floor(days/SYNODIC);let t=REF_NEW+(l+.5)*SYNODIC*864e5;if(t<=+now)t+=SYNODIC*864e5;return new Date(t)}
function renderMoon(){const m=moonData();$('#moonPhaseLabel').textContent=m.name;$('#moonIllumination').textContent=Math.round(m.illum*100)+'%';$('#moonShadow').style.transform=`translateX(${m.phase<=.5?100-m.phase*200:-100+(m.phase-.5)*200}%)`;$('#cycleProgress').style.width=(m.phase*100)+'%';const f=nextFullMoon(),diff=Math.max(0,+f-Date.now());$('#fullMoonDate').textContent=fmtDate(f);$('#fullMoonCountdown').textContent=`${Math.floor(diff/864e5)} d · ${Math.floor(diff/36e5)%24} h · ${Math.floor(diff/6e4)%60} min`}
function tick(){const now=new Date();$('#liveClock').textContent=new Intl.DateTimeFormat(locale(),{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false,timeZone:state.timezone}).format(now);$('#liveDate').textContent=new Intl.DateTimeFormat(locale(),{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:state.timezone}).format(now);renderMoon();renderCurrentHour()}
async function reverseLocation(){try{const r=await fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${state.lat}&longitude=${state.lon}&localityLanguage=${state.lang}`);if(!r.ok)throw new Error();const d=await r.json();state.location=[d.city||d.locality||d.principalSubdivision,d.countryName].filter(Boolean).join(', ')||'Current location'}catch{state.location='Current location'}$('#locationName').textContent=state.location;$('#autoLocationLabel').textContent=state.location}
async function fetchWeather(){if(state.lat==null)return;setStatus(T().sync);const q=new URLSearchParams({latitude:state.lat,longitude:state.lon,timezone:'auto',forecast_days:'3',current:'temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,surface_pressure,wind_speed_10m',hourly:'temperature_2m,precipitation_probability,weather_code',daily:'sunrise,sunset'});try{const r=await fetch(`https://api.open-meteo.com/v1/forecast?${q}`);if(!r.ok)throw new Error('weather');const d=await r.json();state.timezone=d.timezone||state.timezone;state.weather=d;renderWeather(d);localStorage.setItem('lunarisWeather',JSON.stringify({location:state.location,data:d,time:Date.now()}));setStatus(T().updated+' '+fmtTime(new Date()))}catch(err){const c=JSON.parse(localStorage.getItem('lunarisWeather')||'null');if(c){state.location=c.location||state.location;state.weather=c.data;renderWeather(c.data,true);setStatus('Offline cache')}else setStatus('No data')}}
function renderWeather(d,cached=false){const c=d.current,w=weatherCodes[c.weather_code]||['—','◌'];$('#locationName').textContent=state.location;$('#autoLocationLabel').textContent=state.location;$('#temperature').textContent=Math.round(c.temperature_2m)+'°';$('#weatherText').textContent=w[0];$('#weatherIcon').textContent=w[1];$('#feelsLike').textContent=T().feels+' '+Math.round(c.apparent_temperature)+'°';$('#wind').textContent=Math.round(c.wind_speed_10m)+' km/h';$('#humidity').textContent=c.relative_humidity_2m+'%';$('#pressure').textContent=Math.round(c.surface_pressure)+' hPa';$('#dataUpdated').textContent=(cached?'Offline · ':T().updated+' ')+fmtTime(c.time);const idx=Math.max(0,d.hourly.time.findIndex(x=>new Date(x)>=new Date(c.time)));$('#hourlyForecast').innerHTML=d.hourly.time.slice(idx,idx+8).map((time,i)=>{const code=d.hourly.weather_code[idx+i],icon=(weatherCodes[code]||['','◌'])[1];return `<div class="hour"><time>${i?fmtTime(time):T().current}</time><i>${icon}</i><b>${Math.round(d.hourly.temperature_2m[idx+i])}°</b><span>${d.hourly.precipitation_probability[idx+i]}%</span></div>`}).join('');$('#sunrise').textContent=fmtTime(d.daily.sunrise[0]);$('#sunset').textContent=fmtTime(d.daily.sunset[0]);buildHours(d.daily.sunrise[0],d.daily.sunset[0],d.daily.sunrise[1]);renderSun()}
function buildHours(riseISO,setISO,nextRiseISO){const rise=+new Date(riseISO),set=+new Date(setISO),nextRise=+new Date(nextRiseISO),dl=(set-rise)/12,nl=(nextRise-set)/12,start=order.indexOf(dayRulers[new Date(rise).getDay()]);state.hours=[];for(let i=0;i<24;i++){const day=i<12,s=day?rise+i*dl:set+(i-12)*nl,e=s+(day?dl:nl);state.hours.push({i:i+1,day,start:s,end:e,planet:order[(start+i)%7]})}renderHours();renderCurrentHour()}
function renderHours(){if(!$('#planetaryHours'))return;const now=Date.now(),items=state.hours.filter(h=>state.filter==='all'||state.filter==='day'&&h.day||state.filter==='night'&&!h.day);$('#planetaryHours').innerHTML=items.map(h=>{const p=planets[h.planet],cur=now>=h.start&&now<h.end;return `<button class="hour-card ${cur?'current':''}" data-index="${h.i-1}"><span class="n">${h.day?T().day:T().night} · ${h.i>12?h.i-12:h.i}</span><span class="planet">${p.seal} ${p.name}</span><span class="range">${fmtTime(h.start)} — ${fmtTime(h.end)}</span><span class="hour-purpose">${p.tags.slice(0,2).join(' · ')}</span></button>`}).join('')}
function renderCurrentHour(){const h=state.hours.find(x=>Date.now()>=x.start&&Date.now()<x.end);if(!h)return;const p=planets[h.planet],remain=Math.max(0,h.end-Date.now());$('#currentPlanetSeal').textContent=p.seal;$('#currentPlanetName').textContent=p.name;$('#currentHourRange').textContent=`${fmtTime(h.start)} — ${fmtTime(h.end)}`;$('#currentPlanetTags').innerHTML=p.tags.map(x=>`<span>${x}</span>`).join('');$('#planetHourNote').textContent=p.note;$('#planetHourProgress').style.width=Math.max(0,Math.min(100,(Date.now()-h.start)/(h.end-h.start)*100))+'%';$('#hourRemaining').textContent=Math.floor(remain/60000)+' min'}
function renderSun(){if(!state.weather)return;const r=+new Date(state.weather.daily.sunrise[0]),s=+new Date(state.weather.daily.sunset[0]),p=Math.max(0,Math.min(1,(Date.now()-r)/(s-r)));$('#sunPoint').style.left=(8+p*84)+'%';$('#sunPoint').style.bottom=(18+Math.sin(Math.PI*p)*72)+'px'}
function fallback(){const c=JSON.parse(localStorage.getItem('lunarisCoords')||'null');if(c){state.lat=c.lat;state.lon=c.lon;$('#autoLocationLabel').textContent='Last known location';fetchWeather()}else{state.lat=52.2297;state.lon=21.0122;state.location='Warszawa, Polska';$('#autoLocationLabel').textContent=T().geoDenied;fetchWeather()}}
function locate(){if(!navigator.geolocation)return fallback();setStatus(T().locating);navigator.geolocation.getCurrentPosition(async p=>{state.lat=p.coords.latitude;state.lon=p.coords.longitude;localStorage.setItem('lunarisCoords',JSON.stringify({lat:state.lat,lon:state.lon,time:Date.now()}));await reverseLocation();await fetchWeather()},()=>{fallback();toast(T().geoDenied)},{enableHighAccuracy:true,timeout:18000,maximumAge:120000})}
function getPractices(){try{return JSON.parse(localStorage.getItem('lunarisPractices')||'[]')}catch{return[]}}
function savePractices(v){localStorage.setItem('lunarisPractices',JSON.stringify(v))}
function openPlanner(pref={}){const n=new Date(Date.now()+3600000);$('#practiceTitle').value=pref.title||'';$('#practiceDate').value=pref.date||localDate(n);$('#practiceTime').value=pref.time||localTime(n);$('#practiceNotes').value=pref.notes||'';$('#plannerModal').hidden=false;requestAnimationFrame(()=>$('#plannerModal').classList.add('open'))}
function closePlanner(){$('#plannerModal').classList.remove('open');setTimeout(()=>$('#plannerModal').hidden=true,220)}
async function requestNotifications(){if(!('Notification' in window))return false;if(Notification.permission==='granted')return true;if(Notification.permission==='denied')return false;return (await Notification.requestPermission())==='granted'}
function schedule(){state.timers.forEach(clearTimeout);state.timers.clear();const now=Date.now();getPractices().forEach(p=>{if(!p.reminder||p.notified)return;const at=+new Date(`${p.date}T${p.time}`)-3600000,delay=at-now;if(delay>0&&delay<2147483647)state.timers.set(p.id,setTimeout(()=>notifyPractice(p),delay));else if(delay<=0&&+new Date(`${p.date}T${p.time}`)>now)notifyPractice(p)})}
function notifyPractice(p){const body=`${p.title} · ${p.time}`;if(navigator.serviceWorker?.controller)navigator.serviceWorker.controller.postMessage({type:'SHOW_NOTIFICATION',title:'LUNARIS',body,tag:'practice-'+p.id});else if(Notification.permission==='granted')new Notification('LUNARIS',{body,icon:'assets/icon-192.png'});savePractices(getPractices().map(x=>x.id===p.id?{...x,notified:true}:x));renderPractices()}
function renderPractices(){const now=Date.now(),list=getPractices().filter(x=>+new Date(`${x.date}T${x.time}`)>now-86400000).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));const forms=T().records,word=list.length===1?forms[0]:list.length<5?forms[1]:forms[2];$('#practiceCount').textContent=list.length+' '+word;const next=list.find(x=>+new Date(`${x.date}T${x.time}`)>now);$('#nextPractice').innerHTML=next?`<span class="eyebrow">${T().nearest}</span><div><strong>${esc(next.title)}</strong><span>${fmtDate(new Date(`${next.date}T${next.time}`))}</span></div><i>${next.reminder?'🔔':'○'}</i>`:`<div class="empty-next"><span>✦</span><b>${T().nothing}</b><small>${T().first}</small></div>`;$('#practices').innerHTML=list.length?list.map(x=>`<article class="practice-item"><div class="practice-date"><b>${new Date(x.date+'T'+x.time).getDate()}</b><span>${new Intl.DateTimeFormat(locale(),{month:'short'}).format(new Date(x.date+'T'+x.time))}</span></div><div class="practice-main"><h4>${esc(x.title)}</h4><p>${esc(x.time)} · ${esc(x.type)}</p>${x.notes?`<small>${esc(x.notes)}</small>`:''}</div><span>${x.reminder?'🔔':'○'}</span><button class="delete-btn" data-id="${x.id}">×</button></article>`).join(''):`<div class="empty">${T().empty}</div>`}
function prefillHour(i){const h=state.hours[i];if(!h)return;const p=planets[h.planet],d=new Date(h.start);openPlanner({title:p.name,date:localDate(d),time:localTime(d),notes:p.note})}
function initSky(){const c=$('#sky'),ctx=c.getContext('2d');let stars=[];function resize(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);stars=Array.from({length:Math.min(260,Math.round(innerWidth/4))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.1+.15,a:Math.random(),v:Math.random()*.006+.001}))}function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);for(const s of stars){s.a+=s.v;if(s.a>1||s.a<.12)s.v*=-1;ctx.globalAlpha=s.a;ctx.fillStyle='#efe9dd';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;requestAnimationFrame(draw)}addEventListener('resize',resize);resize();draw()}
function openInstall(){const modal=$('#installModal'),ios=/iphone|ipad|ipod/i.test(navigator.userAgent);$('#installTitle').textContent=T().installTitle;$('#installLead').textContent=T().installLead;$('#installSteps').innerHTML=`<div class="install-step"><b>1</b><span>${ios?T().ios:T().manual}</span></div>`;$('#installPrimaryAction').hidden=!state.installPrompt;modal.hidden=false;requestAnimationFrame(()=>modal.classList.add('open'))}
function closeInstall(){$('#installModal').classList.remove('open');setTimeout(()=>$('#installModal').hidden=true,220)}
async function performInstall(){if(!state.installPrompt)return openInstall();state.installPrompt.prompt();const r=await state.installPrompt.userChoice;state.installPrompt=null;if(r.outcome==='accepted'){closeInstall();toast(T().installed)}}
function bind(){['languageSelect','languageSelectMobile'].forEach(id=>$('#'+id)?.addEventListener('change',e=>applyLanguage(e.target.value)));$('#quickPlanBtn').onclick=()=>openPlanner();$('#newPracticeBtn').onclick=()=>openPlanner();$('#planCurrentHourBtn').onclick=()=>{const h=state.hours.find(x=>Date.now()>=x.start&&Date.now()<x.end);h?prefillHour(h.i-1):openPlanner()};$('#locateBtn').onclick=locate;$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');$('.sidebar nav').onclick=()=>$('.sidebar').classList.remove('open');$$('[data-close-modal]').forEach(x=>x.onclick=closePlanner);$$('[data-close-install]').forEach(x=>x.onclick=closeInstall);$('#installBtn').onclick=openInstall;$('#sidebarInstallBtn').onclick=openInstall;$('#installPrimaryAction').onclick=performInstall;$('#planetaryHours').onclick=e=>{const b=e.target.closest('.hour-card');if(b)prefillHour(+b.dataset.index)};$$('.segmented button').forEach(b=>b.onclick=()=>{$$('.segmented button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.hours;renderHours()});$('#practices').onclick=e=>{const b=e.target.closest('.delete-btn');if(!b)return;savePractices(getPractices().filter(x=>x.id!=b.dataset.id));renderPractices();schedule()};$('#practiceForm').onsubmit=async e=>{e.preventDefault();const eventAt=+new Date(`${$('#practiceDate').value}T${$('#practiceTime').value}`);if(eventAt<=Date.now())return toast('Choose future time');const wants=$('#practiceReminder').checked,allowed=wants?await requestNotifications():false;const list=getPractices();list.push({id:Date.now(),title:$('#practiceTitle').value.trim(),date:$('#practiceDate').value,time:$('#practiceTime').value,type:$('#practiceType').value,notes:$('#practiceNotes').value.trim(),reminder:wants&&allowed,notified:false});savePractices(list);closePlanner();renderPractices();schedule();toast(T().saved)};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;$$('#installBtn,#sidebarInstallBtn').forEach(b=>b.classList.add('install-ready'))});window.addEventListener('appinstalled',()=>toast(T().installed))}
function boot(){try{bind();initSky();applyLanguage(state.lang);renderMoon();renderPractices();tick();locate();schedule();setInterval(tick,1000);setInterval(schedule,60000);if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(console.error);document.documentElement.classList.add('app-ready')}catch(err){console.error(err);setStatus('Interface error');toast('Reload the page')}}
document.addEventListener('DOMContentLoaded',boot);
